### PR TITLE
chore: Rework build and upgrade to Angular 2 RC6

### PR DESCRIPTION
**Pull request by MikeRyanDev**
Upgrades @ngrx/db to Angular 2 RC6. New setup API:

``` ts
import { DBModule } from '@ngrx/db';

@NgModule({
  imports: [
    DBModule.provideDB(schema)
  ]
})
export class AppModule { }
```

Also includes new build and test pipeline:
- Build artifacts created in ./release (this is what gets published to npm)
- Builds JS to ES5 with ES2015 modules using @angular/compiler-cli
- Sourcemaps should work 🙏 
- Test coverage should work 🙏 
- Builds UMD bundles in ./release/bundles

If above build process works I'll send a PR to every ngrx project with the same setup.

cc @brandonroberts

### CODE REVIEW

**Comment by brandonroberts** [comment]
Did you test the sourcemaps?

**Comment by MikeRyanDev** [comment]
@brandonroberts Yes I have, but would like additional verification of this.

**Comment by robwormald** [comment]
this LGTM 👍

**Comment by MikeRyanDev** [comment]
Released as v2.0

**Pull request merged**
